version: "3.4"
services:
 dummy:
    image: arm32v7/api:dummy
    container_name: ${DUMMY_CONTAINER_NAME}
    privileged: true
    working_dir: /webapps
    # ports:
    #   - 6000:8080
    environment:
      # DUMMY_RUNNER: dummy
      DUMMY_URL: 192.168.3.239:3306/dummy
      DOCKER_SOCKET: /var/run/docker.sock
      # DOCKER_ENDPOINT: 172.18.0.1:2375
      DOCKER_CONTAINER: biliya-api
      ROLLBACK_KEEP_NUM: 2
      DEPLOY_OPT: ${DEPLOY_OPT} # dummy: continer; restart: restart container; deploy: deploy only
      #GREENFIELD: dummy
      # URL_SHORT: 192.168.3.239:3306/dummy
      # USERNAME: root
      # PASSWORD: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/lib:/webapps/lib
      - ./data/classes:/webapps/classes
      - ./data/indexes:/webapps/indexes
      - ${DUMMY_WORKING_DIR}:/webapps
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
