#data-stage
FROM zelejs/allin-web:git as data

#builk-stage
FROM arm32v7/centos:latest

RUN yum -y update && yum -y install git

COPY --from=data /var/.ssh/arm/id_rsa /root/.ssh/id_rsa
COPY --from=data /var/.ssh/arm/id_rsa.pub /root/.ssh/id_rsa.pub


RUN git config --global user.name "git@allin-web"
RUN git config --global user.email "git@allin-web"
